[Unit]
Wants=proton-wg@lidarr.service proton-wg@prowlarr.service proton-wg@radarr.service proton-wg@sonarr.service proton-wg@whisparr.service
After=proton-wg@lidarr.service proton-wg@prowlarr.service proton-wg@radarr.service proton-wg@sonarr.service proton-wg@whisparr.service